In [280]:
import pandas as pd
import numpy as np

In [281]:
#clubs_fr.csv : Une liste des clubs français avec quelques stats sur la constitution (récente) de l’équipe
clubs_fr=pd.read_csv("clubs_fr.csv")
#game_events.csv :  Un ensemble d’actions pour chaque joueur pendant chaque match, peut compléter les informations sur un joueur, vous allez sûrement devoir aggreger des informations ce jeu (par exemple comptez le nombre de passe décisive, d’arrêt etc...)
game_events=pd.read_csv("game_events.csv")
#game_lineups.csv : La constitution des équipes pour chaque match, vous n’avez pas la constitution pour les matchs récents.
game_lineups=pd.read_csv("game_lineups.csv")
#match_2023.csv : La liste des matchs à prédire, vous n’avez pas le résultat, il sera dévoilé après la fin du projet.
match_2023=pd.read_csv("match_2023.csv")
#matchs_2013_2022.csv : La liste de tous les matchs avant 2023, avec le résultat associé
matchs_2013_2022=pd.read_csv("matchs_2013_2022.csv")
#player_appearance.csv : Un ensemble d’info simple sur chaque joueur pendant chaque match (nombre de buts, nombre de cartons)
player_appearance=pd.read_csv("player_appearance.csv")
#player_valuation_before_season.csv : Pour chaque joueur, sa valeur sur le marché, à une certaine date, à vous de transformer et d’utiliser cette information à bonne escient.
player_valuation_before_season=pd.read_csv("player_valuation_before_season.csv")

C:\Users\pbria\AppData\Local\Temp\ipykernel_20692\1178837080.py:6: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  game_lineups=pd.read_csv("game_lineups.csv")

In [282]:
#Nettoyage et analyse de matchs_2013_2022

In [283]:
matchs_2013_2022

,Unnamed: 0,game_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type,results
0,12,2330874,2013,8. Matchday,2013-09-28,618,595,2,2,6.0,...,Stade Geoffroy-Guichard,31952.0,Antony Gautier,4-3-3 Attacking,4-2-3-1,AS Saint-Étienne,SC Bastia,2:2,domestic_league,0
1,13,2330880,2013,10. Matchday,2013-10-19,14171,855,1,2,16.0,...,Parc des Sports d’Annecy,8620.0,Philippe Kalt,4-4-2 double 6,4-4-2 double 6,Thonon Évian Grand Genève FC,EA Guingamp,1:2,domestic_league,-1
2,14,2330916,2013,15. Matchday,2013-11-30,1423,1082,0,1,18.0,...,Stade du Hainaut,14874.0,Bartolomeu Varela,4-4-2 double 6,4-3-1-2,Valenciennes FC,Lille Olympique Sporting Club Lille Métropole,0:1,domestic_league,-1
3,15,2331018,2013,21. Matchday,2014-01-18,273,14171,0,0,15.0,...,Roazhon Park,13391.0,Benoît Millot,4-3-3 Attacking,4-2-3-1,Stade Rennais Football Club,Thonon Évian Grand Genève FC,0:0,domestic_league,0
4,16,2331034,2013,24. Matchday,2014-02-08,1147,273,3,1,20.0,...,Stade François-Coty,5981.0,Benoît Bastien,4-1-4-1,4-3-3 Defending,AC Ajaccio,Stade Rennais Football Club,3:1,domestic_league,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4073,66083,3199491,2019,14. Matchday,2019-11-24,40,162,2,1,4.0,...,Matmut Atlantique,34554.0,Benoît Millot,3-4-3,3-5-2 flat,FC Girondins Bordeaux,Association sportive de Monaco Football Club,2:1,domestic_league,1
4074,67000,3394982,2020,36. Matchday,2021-05-09,667,969,2,3,16.0,...,Stade de la Meinau,NaN,Jérôme Miguelgorry,4-4-2 Diamond,4-3-3 Attacking,Racing Club de Strasbourg Alsace,Montpellier Hérault Sport Club,2:3,domestic_league,-1
4075,67467,3047720,2018,20. Matchday,2019-01-13,415,667,1,2,14.0,...,Stadium Municipal,15465.0,Hakim Ben El Hadj,5-4-1,5-3-2,Toulouse Football Club,Racing Club de Strasbourg Alsace,1:2,domestic_league,-1
4076,67720,3199559,2019,21. Matchday,2020-01-25,162,667,1,3,13.0,...,Stade Louis-II,4800.0,Eric Wattellier,4-3-3 Attacking,5-3-2,Association sportive de Monaco Football Club,Racing Club de Strasbourg Alsace,1:3,domestic_league,-1
4077,67721,3394685,2020,13. Matchday,2020-12-06,40,3911,1,0,10.0,...,Matmut Atlantique,NaN,Frank Schneider,4-4-2 double 6,4-4-2 double 6,FC Girondins Bordeaux,Stade brestois 29,1:0,domestic_league,1

In [284]:
matchs_2013_2022.corr()

,Unnamed: 0,game_id,season,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,away_club_position,attendance,results
Unnamed: 0,1.000000,0.069607,0.068005,-0.007849,0.007258,0.006680,0.000745,-0.010793,0.016952,-0.000534,0.011645
game_id,0.069607,1.000000,0.994613,-0.073932,-0.074094,0.017540,0.075746,0.005728,-0.005589,0.039172,-0.038518
season,0.068005,0.994613,1.000000,-0.083840,-0.084085,0.017994,0.072514,0.004980,-0.004718,0.038473,-0.037163
home_club_id,-0.007849,-0.073932,-0.083840,1.000000,-0.029921,-0.050096,0.044893,0.234411,-0.024855,-0.203569,-0.063275
away_club_id,0.007258,-0.074094,-0.084085,-0.029921,1.000000,0.044721,-0.061780,-0.030703,0.238255,-0.036681,0.080797
home_club_goals,0.006680,0.017540,0.017994,-0.050096,0.044721,1.000000,-0.086822,-0.334554,0.281564,0.167848,0.631402
away_club_goals,0.000745,0.075746,0.072514,0.044893,-0.061780,-0.086822,1.000000,0.257990,-0.295657,-0.059865,-0.632213
home_club_position,-0.010793,0.005728,0.004980,0.234411,-0.030703,-0.334554,0.257990,1.000000,-0.140522,-0.486814,-0.395606
away_club_position,0.016952,-0.005589,-0.004718,-0.024855,0.238255,0.281564,-0.295657,-0.140522,1.000000,-0.066704,0.392833
attendance,-0.000534,0.039172,0.038473,-0.203569,-0.036681,0.167848,-0.059865,-0.486814,-0.066704,1.000000,0.122904
results,0.011645,-0.038518,-0.037163,-0.063275,0.080797,0.631402,-0.632213,-0.395606,0.392833,0.122904,1.000000

In [285]:
matchs_2013_2022=matchs_2013_2022.drop(columns="Unnamed: 0") #Colonne inutile
matchs_2013_2022=matchs_2013_2022.drop(columns="season") #On peut recuperer la saison via la date donc pas besoin
matchs_2013_2022=matchs_2013_2022.drop(columns="home_club_goals") #Le score ne nous interesse pas seul le resultat compte
matchs_2013_2022=matchs_2013_2022.drop(columns="away_club_goals")#Le score ne nous interesse pas seul le resultat compte
matchs_2013_2022=matchs_2013_2022.drop(columns="aggregate")#Le score ne nous interesse pas seul le resultat compte
matchs_2013_2022=matchs_2013_2022.drop(columns="competition_type")#Ils sont tous en domestic_league
matchs_2013_2022=matchs_2013_2022.drop(columns="home_club_name")#On a deja la club ID pas besoin du nom
matchs_2013_2022=matchs_2013_2022.drop(columns="away_club_name")#On a deja la club ID pas besoin du nom
matchs_2013_2022=matchs_2013_2022.drop(columns="home_club_formation")#On ne connait les compositions que quelques heures avant le match
matchs_2013_2022=matchs_2013_2022.drop(columns="away_club_formation")#On ne connait les compositions que quelques heures avant le match
#matchs_2013_2022=matchs_2013_2022.drop(columns="home_club_manager_name")#Sur la saison le manager sera toujours le meme ?
#matchs_2013_2022=matchs_2013_2022.drop(columns="away_club_manager_name")
matchs_2013_2022=matchs_2013_2022.drop(columns="referee") #L'arbitre ne devrait pas favoriser une equipe 
matchs_2013_2022=matchs_2013_2022.drop(columns="round")

matchs_2013_2022

,game_id,date,home_club_id,away_club_id,home_club_position,away_club_position,home_club_manager_name,away_club_manager_name,stadium,attendance,results
0,2330874,2013-09-28,618,595,6.0,8.0,Christophe Galtier,Frédéric Hantz,Stade Geoffroy-Guichard,31952.0,0
1,2330880,2013-10-19,14171,855,16.0,10.0,Pascal Dupraz,Jocelyn Gourvennec,Parc des Sports d’Annecy,8620.0,-1
2,2330916,2013-11-30,1423,1082,18.0,2.0,Ariel Jacobs,René Girard,Stade du Hainaut,14874.0,-1
3,2331018,2014-01-18,273,14171,15.0,17.0,Philippe Montanier,Pascal Dupraz,Roazhon Park,13391.0,0
4,2331034,2014-02-08,1147,273,20.0,15.0,Christian Bracconi,Philippe Montanier,Stade François-Coty,5981.0,1
...,...,...,...,...,...,...,...,...,...,...,...
4073,3199491,2019-11-24,40,162,4.0,14.0,Paulo Sousa,Leonardo Jardim,Matmut Atlantique,34554.0,1
4074,3394982,2021-05-09,667,969,16.0,8.0,Thierry Laurey,Michel Der Zakarian,Stade de la Meinau,NaN,-1
4075,3047720,2019-01-13,415,667,14.0,8.0,Alain Casanova,Thierry Laurey,Stadium Municipal,15465.0,-1
4076,3199559,2020-01-25,162,667,13.0,8.0,Robert Moreno,Thierry Laurey,Stade Louis-II,4800.0,-1
4077,3394685,2020-12-06,40,3911,10.0,12.0,Jean-Louis Gasset,Olivier Dall'Oglio,Matmut Atlantique,NaN,1

In [286]:
matchs_2013_2022.corr()

,game_id,home_club_id,away_club_id,home_club_position,away_club_position,attendance,results
game_id,1.000000,-0.073932,-0.074094,0.005728,-0.005589,0.039172,-0.038518
home_club_id,-0.073932,1.000000,-0.029921,0.234411,-0.024855,-0.203569,-0.063275
away_club_id,-0.074094,-0.029921,1.000000,-0.030703,0.238255,-0.036681,0.080797
home_club_position,0.005728,0.234411,-0.030703,1.000000,-0.140522,-0.486814,-0.395606
away_club_position,-0.005589,-0.024855,0.238255,-0.140522,1.000000,-0.066704,0.392833
attendance,0.039172,-0.203569,-0.036681,-0.486814,-0.066704,1.000000,0.122904
results,-0.038518,-0.063275,0.080797,-0.395606,0.392833,0.122904,1.000000

In [287]:
#Nettoyage et analyse de matchs_2023

In [288]:
match_2023

,game_id,date,home_club_id,away_club_id,home_club_manager_name,away_club_manager_name,stadium,attendance,referee,home_club_name,away_club_name,competition_type
0,4094596,2023-08-26,583,826,Luis Enrique,Franck Haise,Parc des Princes,47000.0,François Letexier,Paris Saint-Germain Football Club,Racing Club de Lens,domestic_league
1,4094622,2023-09-16,826,347,Franck Haise,László Bölöni,Stade Bollaert-Delelis,37988.0,Stéphanie Frappart,Racing Club de Lens,Football Club de Metz,domestic_league
2,4094630,2023-09-24,969,273,Michel Der Zakarian,Bruno Génésio,Stade de la Mosson,15430.0,Stéphanie Frappart,Montpellier Hérault Sport Club,Stade Rennais Football Club,domestic_league
3,4094647,2023-10-07,347,417,László Bölöni,Francesco Farioli,Stade Saint-Symphorien,23160.0,Jérôme Brisard,Football Club de Metz,Olympique Gymnaste Club Nice Côte d'Azur,domestic_league
4,4094696,2023-12-03,244,273,Gennaro Gattuso,Julien Stéphan,Orange Vélodrome,54162.0,Willy Delajod,Olympique de Marseille,Stade Rennais Football Club,domestic_league
...,...,...,...,...,...,...,...,...,...,...,...,...
265,4094819,2024-03-31,738,969,Luka Elsner,Michel Der Zakarian,Stade Océane,20556.0,Mathieu Vernice,Le Havre Athletic Club,Montpellier Hérault Sport Club,domestic_league
266,4094840,2024-04-21,415,244,Carles Martínez,Jean-Louis Gasset,Stadium Municipal,29809.0,Clément Turpin,Toulouse Football Club,Olympique de Marseille,domestic_league
267,4094776,2024-02-25,583,273,Luis Enrique,Julien Stéphan,Parc des Princes,47874.0,Bastien Dechepy,Paris Saint-Germain Football Club,Stade Rennais Football Club,domestic_league
268,4094786,2024-03-03,415,417,Carles Martínez,Francesco Farioli,Stadium Municipal,25507.0,Jérémie Pignard,Toulouse Football Club,Olympique Gymnaste Club Nice Côte d'Azur,domestic_league
269,4094777,2024-02-24,667,3911,Patrick Vieira,Éric Roy,Stade de la Meinau,25140.0,Jérôme Brisard,Racing Club de Strasbourg Alsace,Stade brestois 29,domestic_league

In [289]:
match_2023=match_2023.drop(columns="competition_type") #Tous en domestic league donc pas important
match_2023=match_2023.drop(columns="home_club_name") #On a deja l'id du club pas besoin du nom
match_2023=match_2023.drop(columns="away_club_name") #On a deja l'id du club pas besoin du nom

match_2023

,game_id,date,home_club_id,away_club_id,home_club_manager_name,away_club_manager_name,stadium,attendance,referee
0,4094596,2023-08-26,583,826,Luis Enrique,Franck Haise,Parc des Princes,47000.0,François Letexier
1,4094622,2023-09-16,826,347,Franck Haise,László Bölöni,Stade Bollaert-Delelis,37988.0,Stéphanie Frappart
2,4094630,2023-09-24,969,273,Michel Der Zakarian,Bruno Génésio,Stade de la Mosson,15430.0,Stéphanie Frappart
3,4094647,2023-10-07,347,417,László Bölöni,Francesco Farioli,Stade Saint-Symphorien,23160.0,Jérôme Brisard
4,4094696,2023-12-03,244,273,Gennaro Gattuso,Julien Stéphan,Orange Vélodrome,54162.0,Willy Delajod
...,...,...,...,...,...,...,...,...,...
265,4094819,2024-03-31,738,969,Luka Elsner,Michel Der Zakarian,Stade Océane,20556.0,Mathieu Vernice
266,4094840,2024-04-21,415,244,Carles Martínez,Jean-Louis Gasset,Stadium Municipal,29809.0,Clément Turpin
267,4094776,2024-02-25,583,273,Luis Enrique,Julien Stéphan,Parc des Princes,47874.0,Bastien Dechepy
268,4094786,2024-03-03,415,417,Carles Martínez,Francesco Farioli,Stadium Municipal,25507.0,Jérémie Pignard
269,4094777,2024-02-24,667,3911,Patrick Vieira,Éric Roy,Stade de la Meinau,25140.0,Jérôme Brisard

In [290]:
match_2023=match_2023.drop(columns="home_club_manager_name") #Le nom du manager va rester le meme pour toute la saison donc inutile de garder cette colonne
match_2023=match_2023.drop(columns="away_club_manager_name") #Le nom du manager va rester le meme pour toute la saison donc inutile de garder cette colonne
match_2023=match_2023.drop(columns="referee")#L'arbitre n'influence pas sur le resultat du match en tout cas pas en faveur d'une ou de l'autre equipe

match_2023

,game_id,date,home_club_id,away_club_id,stadium,attendance
0,4094596,2023-08-26,583,826,Parc des Princes,47000.0
1,4094622,2023-09-16,826,347,Stade Bollaert-Delelis,37988.0
2,4094630,2023-09-24,969,273,Stade de la Mosson,15430.0
3,4094647,2023-10-07,347,417,Stade Saint-Symphorien,23160.0
4,4094696,2023-12-03,244,273,Orange Vélodrome,54162.0
...,...,...,...,...,...,...
265,4094819,2024-03-31,738,969,Stade Océane,20556.0
266,4094840,2024-04-21,415,244,Stadium Municipal,29809.0
267,4094776,2024-02-25,583,273,Parc des Princes,47874.0
268,4094786,2024-03-03,415,417,Stadium Municipal,25507.0
269,4094777,2024-02-24,667,3911,Stade de la Meinau,25140.0

In [291]:
#Nettoyage et analyse de player_appearance

In [292]:
player_appearance

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,2229837_108830,2229837,108830,415,3205,2012-08-10,Aymen Abdennour,FR1,1,0,0,0,90
1,2229837_113707,2229837,113707,969,1082,2012-08-10,Rémy Cabella,FR1,1,0,0,0,42
2,2229837_126767,2229837,126767,415,3205,2012-08-10,Ali Ahamada,FR1,0,0,0,0,90
3,2229837_126796,2229837,126796,415,60949,2012-08-10,Adrien Regattin,FR1,0,1,0,0,11
4,2229837_127032,2229837,127032,415,141,2012-08-10,Serge Aurier,FR1,0,1,0,1,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115177,3840454_709482,3840454,709482,1095,1095,2023-06-03,Thierno Baldé,FR1,0,0,0,1,84
115178,3840454_84301,3840454,84301,1082,1082,2023-06-03,Benjamin André,FR1,1,0,0,0,90
115179,3840454_917104,3840454,917104,1095,1095,2023-06-03,Derek Mazou-Sacko,FR1,0,0,0,0,15
115180,3840454_917120,3840454,917120,1095,1095,2023-06-03,Tanguy Zoukrou,FR1,0,0,0,0,90
115181,3840454_973085,3840454,973085,1082,1237,2023-06-03,Carlos Baleba,FR1,0,0,0,0,9

In [293]:
player_appearance=player_appearance.drop(columns="player_name") #On a deja la player_id 
player_appearance=player_appearance.drop(columns="competition_id") #Ils sont tous en FR1 donc pas pertinent 

player_appearance

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,yellow_cards,red_cards,goals,assists,minutes_played
0,2229837_108830,2229837,108830,415,3205,2012-08-10,1,0,0,0,90
1,2229837_113707,2229837,113707,969,1082,2012-08-10,1,0,0,0,42
2,2229837_126767,2229837,126767,415,3205,2012-08-10,0,0,0,0,90
3,2229837_126796,2229837,126796,415,60949,2012-08-10,0,1,0,0,11
4,2229837_127032,2229837,127032,415,141,2012-08-10,0,1,0,1,84
...,...,...,...,...,...,...,...,...,...,...,...
115177,3840454_709482,3840454,709482,1095,1095,2023-06-03,0,0,0,1,84
115178,3840454_84301,3840454,84301,1082,1082,2023-06-03,1,0,0,0,90
115179,3840454_917104,3840454,917104,1095,1095,2023-06-03,0,0,0,0,15
115180,3840454_917120,3840454,917120,1095,1095,2023-06-03,0,0,0,0,90
115181,3840454_973085,3840454,973085,1082,1237,2023-06-03,0,0,0,0,9

In [294]:
#Nettoyage et analyse de clubs_fr

In [295]:
clubs_fr.head()

,club_id,club_code,name,domestic_competition_id,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name
0,969,montpellier-hsc,Montpellier Hérault Sport Club,FR1,25,25.7,12,48.0,8,Stade de la Mosson,32939,+€28.60m,NaN
1,1082,losc-lille,Lille Olympique Sporting Club Lille Métropole,FR1,25,25.4,18,72.0,7,Decathlon Arena-Stade Pierre-Mauroy,50186,+€3.65m,NaN
2,1160,nimes-olympique,Nîmes Olympique,FR1,26,25.4,12,46.2,3,Stade des Antonins,8033,+€2.50m,NaN
3,3911,stade-brest-29,Stade brestois 29,FR1,24,26.0,6,25.0,3,Stade Francis-Le Blé,15220,+€5.10m,NaN
4,595,sc-bastia,SC Bastia,FR1,25,27.6,8,32.0,6,Stade Armand-Cesari,16480,+€480k,NaN

In [296]:
clubs_fr=clubs_fr.drop(columns="domestic_competition_id") #Tous en FR1
clubs_fr=clubs_fr.drop(columns="squad_size") #Ici on suppose qu'elle ne change pas au cours de la saison
clubs_fr=clubs_fr.drop(columns="stadium_seats") #Le stade aura toujours le meme nombre de place donc avec le nom du stade on a deja l'information
clubs_fr=clubs_fr.drop(columns="name") #On a deja l'id du club
clubs_fr=clubs_fr.drop(columns="club_code") #On a deja l'id du club
clubs_fr=clubs_fr.drop(columns="coach_name") #Colonne pleine de NaN, autrement on recuperera le nom du manager autrepart

clubs_fr.head()

,club_id,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,net_transfer_record
0,969,25.7,12,48.0,8,Stade de la Mosson,+€28.60m
1,1082,25.4,18,72.0,7,Decathlon Arena-Stade Pierre-Mauroy,+€3.65m
2,1160,25.4,12,46.2,3,Stade des Antonins,+€2.50m
3,3911,26.0,6,25.0,3,Stade Francis-Le Blé,+€5.10m
4,595,27.6,8,32.0,6,Stade Armand-Cesari,+€480k

In [297]:
#Nettoyage et analyse de game_events

In [298]:
game_events

,Unnamed: 0,game_event_id,date,game_id,minute,type,club_id,player_id,description,player_in_id,player_assist_id
0,6816,5d2b67957aaae6cf2a41e70cb5d4024f,2012-09-22,2223841,73,Substitutions,3911,5399,", Not reported",37516.0,NaN
1,6817,cd511880b945623db06ace57349e45b2,2012-09-22,2223841,76,Goals,3911,24459,", Penalty, 2. Goal of the Season Assist: , Fou...",NaN,24459.0
2,6818,8ca118538b45a24643ab1c9f76e50f6d,2012-09-22,2223841,56,Substitutions,3911,25113,", Not reported",22053.0,NaN
3,6819,aca68dc250aa9a3758fb2243ee679d9d,2012-09-22,2223841,88,Cards,1423,27490,1. Yellow card,NaN,NaN
4,6820,a133e4d7cdccb930f2dc7b4935754a30,2012-09-22,2223841,4,Cards,1423,43960,1. Yellow card,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
40990,595179,3207a9364b650453d83b09bdfbca7209,2023-06-03,3840454,81,Substitutions,1082,392770,NaN,973085.0,NaN
40991,595180,33e97c3325f710fcd0f8aa7e04cf55fd,2023-06-03,3840454,73,Substitutions,1082,400485,NaN,496857.0,NaN
40992,595181,245770e377b0e06e3d87cf3c3147ce33,2023-06-03,3840454,52,Goals,1082,463605,", Left-footed shot, 3. Goal of the Season",NaN,NaN
40993,595182,d2a2bfb139a9512db3283904b59b3f8c,2023-06-03,3840454,75,Substitutions,1095,554251,NaN,568702.0,NaN
40994,595183,6f0004f185acd75d8267cd8ea6d4ace6,2023-06-03,3840454,84,Substitutions,1095,709482,NaN,345748.0,NaN

In [299]:
game_events=game_events.drop(columns="Unnamed: 0")

game_events

,game_event_id,date,game_id,minute,type,club_id,player_id,description,player_in_id,player_assist_id
0,5d2b67957aaae6cf2a41e70cb5d4024f,2012-09-22,2223841,73,Substitutions,3911,5399,", Not reported",37516.0,NaN
1,cd511880b945623db06ace57349e45b2,2012-09-22,2223841,76,Goals,3911,24459,", Penalty, 2. Goal of the Season Assist: , Fou...",NaN,24459.0
2,8ca118538b45a24643ab1c9f76e50f6d,2012-09-22,2223841,56,Substitutions,3911,25113,", Not reported",22053.0,NaN
3,aca68dc250aa9a3758fb2243ee679d9d,2012-09-22,2223841,88,Cards,1423,27490,1. Yellow card,NaN,NaN
4,a133e4d7cdccb930f2dc7b4935754a30,2012-09-22,2223841,4,Cards,1423,43960,1. Yellow card,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
40990,3207a9364b650453d83b09bdfbca7209,2023-06-03,3840454,81,Substitutions,1082,392770,NaN,973085.0,NaN
40991,33e97c3325f710fcd0f8aa7e04cf55fd,2023-06-03,3840454,73,Substitutions,1082,400485,NaN,496857.0,NaN
40992,245770e377b0e06e3d87cf3c3147ce33,2023-06-03,3840454,52,Goals,1082,463605,", Left-footed shot, 3. Goal of the Season",NaN,NaN
40993,d2a2bfb139a9512db3283904b59b3f8c,2023-06-03,3840454,75,Substitutions,1095,554251,NaN,568702.0,NaN
40994,6f0004f185acd75d8267cd8ea6d4ace6,2023-06-03,3840454,84,Substitutions,1095,709482,NaN,345748.0,NaN

In [300]:
#Nettoyage et analyse de game_lineups

In [301]:
game_lineups

,Unnamed: 0,game_lineups_id,date,game_id,player_id,club_id,player_name,type,position,number,team_captain
0,34475,be6532aeff4c40b06e6e0da142da7dd8,2013-08-24,2330825,4811,969,Hilton,starting_lineup,Centre-Back,4,1
1,34476,4b10516c5bf9b2dfac0435c7c2bbf872,2013-08-24,2330825,5303,969,Souleymane Camara,starting_lineup,Left Winger,19,0
2,34477,46552e9ff9777efa2e2d0df3a8147d87,2013-08-24,2330825,5614,750,Cédric Kanté,starting_lineup,Centre-Back,6,1
3,34478,9c10d07e15ca9a537576aa4c04511562,2013-08-24,2330825,5686,969,Laurent Pionnier,starting_lineup,Goalkeeper,1,0
4,34479,d6592bfd4c2c2f06a388086f8b0b714e,2013-08-24,2330825,17693,750,Sébastien Roudet,starting_lineup,Left Winger,18,0
...,...,...,...,...,...,...,...,...,...,...,...
137127,1963687,ade757c794df293894dadc9718772432,2023-06-03,3840454,917104,1095,Derek Mazou-Sacko,substitutes,Central Midfield,28,0
137128,1963688,bc1f8607d3240a8ae1caad1c0bc77b55,2023-06-03,3840454,917120,1095,Tanguy Zoukrou,starting_lineup,Centre-Back,22,0
137129,1963689,f8ec3e99f6b92d3a9c5fd58f226d4fb6,2023-06-03,3840454,923831,1082,Leny Yoro,substitutes,Centre-Back,15,0
137130,1963690,6e0c6c598b740b452e02e026c136fac6,2023-06-03,3840454,973085,1082,Carlos Baleba,substitutes,Defensive Midfield,35,0
137131,1963691,34bbcbdfe31e55c0d250cac9f235cc61,2023-06-03,3840454,982863,1095,Kyliane Dong,substitutes,Right Winger,27,0

In [302]:
game_lineups=game_lineups.drop(columns="Unnamed: 0")

game_lineups

,game_lineups_id,date,game_id,player_id,club_id,player_name,type,position,number,team_captain
0,be6532aeff4c40b06e6e0da142da7dd8,2013-08-24,2330825,4811,969,Hilton,starting_lineup,Centre-Back,4,1
1,4b10516c5bf9b2dfac0435c7c2bbf872,2013-08-24,2330825,5303,969,Souleymane Camara,starting_lineup,Left Winger,19,0
2,46552e9ff9777efa2e2d0df3a8147d87,2013-08-24,2330825,5614,750,Cédric Kanté,starting_lineup,Centre-Back,6,1
3,9c10d07e15ca9a537576aa4c04511562,2013-08-24,2330825,5686,969,Laurent Pionnier,starting_lineup,Goalkeeper,1,0
4,d6592bfd4c2c2f06a388086f8b0b714e,2013-08-24,2330825,17693,750,Sébastien Roudet,starting_lineup,Left Winger,18,0
...,...,...,...,...,...,...,...,...,...,...
137127,ade757c794df293894dadc9718772432,2023-06-03,3840454,917104,1095,Derek Mazou-Sacko,substitutes,Central Midfield,28,0
137128,bc1f8607d3240a8ae1caad1c0bc77b55,2023-06-03,3840454,917120,1095,Tanguy Zoukrou,starting_lineup,Centre-Back,22,0
137129,f8ec3e99f6b92d3a9c5fd58f226d4fb6,2023-06-03,3840454,923831,1082,Leny Yoro,substitutes,Centre-Back,15,0
137130,6e0c6c598b740b452e02e026c136fac6,2023-06-03,3840454,973085,1082,Carlos Baleba,substitutes,Defensive Midfield,35,0
137131,34bbcbdfe31e55c0d250cac9f235cc61,2023-06-03,3840454,982863,1095,Kyliane Dong,substitutes,Right Winger,27,0

In [303]:
#Nettoyage et analyse de player_valuation_before_season

In [304]:
player_valuation_before_season

,player_id,date,market_value_in_eur,current_club_id,player_club_domestic_competition_id
0,773,2004-10-04,3500000,14171,FR1
1,1327,2004-10-04,4000000,1159,FR1
2,1423,2004-10-04,1000000,855,FR1
3,1572,2004-10-04,1000000,162,FR1
4,1613,2004-10-04,200000,855,FR1
...,...,...,...,...,...
30210,478872,2023-07-27,500000,618,FR1
30211,550862,2023-07-27,450000,1420,FR1
30212,363717,2023-07-28,150000,1162,FR1
30213,396131,2023-07-28,150000,1421,FR1
30214,696598,2023-07-28,300000,417,FR1

In [305]:
player_valuation_before_season=player_valuation_before_season.drop(columns="player_club_domestic_competition_id") #Tous en FR1

player_valuation_before_season

       player_id        date  market_value_in_eur  current_club_id
0            773  2004-10-04              3500000            14171
1           1327  2004-10-04              4000000             1159
2           1423  2004-10-04              1000000              855
3           1572  2004-10-04              1000000              162
4           1613  2004-10-04               200000              855
...          ...         ...                  ...              ...
30210     478872  2023-07-27               500000              618
30211     550862  2023-07-27               450000             1420
30212     363717  2023-07-28               150000             1162
30213     396131  2023-07-28               150000             1421
30214     696598  2023-07-28               300000              417

[30215 rows x 4 columns]

In [316]:
#'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#Modification des csv d'entrainement et de prediction
#'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

In [317]:
matchs_2013_2022=matchs_2013_2022.drop(columns="home_club_position") #Position dans le classement ?
matchs_2013_2022=matchs_2013_2022.drop(columns="away_club_position")

In [318]:
#'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
#Modelisation et Prediction
#'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

In [319]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [322]:
features = ['attendance']

In [323]:
X_train = matchs_2013_2022[features]
y_train = matchs_2013_2022['results']

In [324]:
X_test = match_2023[features]
y_test = match_2023['results']

KeyError: 'results'

In [311]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [312]:
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [313]:
y_pred = rf_model.predict(X_val)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [314]:
accuracy = accuracy_score(y_val, y_pred)
print("Accuracy on validation set:", accuracy)

NameError: name 'y_pred' is not defined

In [315]:
print("Classification Report:")
print(classification_report(y_val, y_pred))

Classification Report:

NameError: name 'y_pred' is not defined